### ISSUE TITLE
Fix readme examples

### ISSUE THREAD

**Issue by roll** [frictionlessdata/datapackage-js#44]
# Overview

Some of them contain typos like `import { Datapackage } from 'datapackage'` (now it's without `{}`).

# Tasks

- [ ] review all examples
- [ ] fix broken examples

**Comment by dumyan** [comment]
Currently the curly brackets are needed because we don't have default export from index.js, just separate exports for `Datapackage`, `Profiles` and `validate`.

What we can do is add a default export for `Datapackage` class and use it without the curly brackets.

The README tests are included in the test suite running on travis, also I have checked it locally and everything works fine. Maybe you got timeout errors because some of the README tests are fetching the profiles remotely?

**Comment by roll** [comment]
It's pretty OK for use to have `Datapackage, Resource and validate` as equal top-level components so I suppose it's only about fixing import in examples.

Here we're getting a feedback - https://gitter.im/frictionlessdata/chat

**Comment by roll** [comment]
Also we could just copy our readme examples as a part of https://github.com/frictionlessdata/datapackage-js/issues/33
